### PR TITLE
support for resolved symlinks in copytree

### PR DESCRIPTION
**Pull request by brno32**
Fixes https://github.com/jborean93/smbprotocol/issues/221

### CODE REVIEW

**Comment by jborean93** [comment]
Just an FYI the Samba target doesn't support symlinks so you'll need to only run the symlink tests on Windows.

**Comment by Neustradamus** [comment]
@brno32: Why have you closed this PR?

**Comment by Neustradamus** [comment]
@jborean93: Can you look?

**Comment by jborean93** [comment]
It's up to @brno32 if they wish to continue with the PR or not. I assume they either don't have the time to contribute anymore or lost interest in this particular feature, both of which are perfectly fine.

**Pull request closed without merging**
